spring:
  data:
    mongodb:
      host: 10.250.250.49
      port: 28027
      username: bitacora
      password: bitacora
      database: bitacora
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
